### ISSUE TITLE
Cannot read properties of undefined (reading 'getSeqFn')

### ISSUE THREAD

**Issue by swampthang** [scribbletune/scribbletune#166] opened 2022-05-12 19:04 UTC
Thanks for making this available! Hoping to get it working. 

I'm running webpack (using a template.html for publishing to dist) which results in dist/index.html of..
```
<!DOCTYPE html>
<html lang="en"><head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Web Audio App</title>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/tone/14.7.43/Tone.js"></script>
<script defer="" src="bundle784a59f78ebc397c11b3.js"></script></head>
<body>
  <div class="container">
    <div>
      <p>The Audio context needs to be started by a user gesture.</p>
      <button id="start">Start context</button>  
    </div>
    <div>
      <p>Once audio context is started by a user gesture, you can use the start/stop methods on clip objects.</p>
      <button id="play">Play</button>
      <button id="stop">Stop</button>
    </div>
  </div>

</body></html>
```
I'm using your example from [here](https://scribbletune.com/documentation/core/clip)...
```
import { clip } from 'scribbletune/browser'

const btnStart = document.getElementById('start');
const btnPlay = document.getElementById('play');
const btnStop = document.getElementById('stop');

btnStart.addEventListener('click', () => {
    Tone.context.resume().then(() => Tone.Transport.start());
});

const simpleLoop = clip({ synth: 'Synth', notes: 'c4', pattern: 'x' });
btnPlay.addEventListener('click', () => {
    simpleLoop.start();
});

btnStop.addEventListener('click', () => {
  simpleLoop.stop();
});

```
When i run 'webpack serve' and the page opens, I see this in the console:
![Screen Shot 2022-05-12 at 2 02 17 PM](https://user-images.githubusercontent.com/428757/168149345-dfac6254-287f-4156-8d6f-504c9c03274e.png)

I've tried npm installing tone.js and importing but no luck. Any idea what I may be able to do to get this working?

Thanks again!

**Comment by walmik** [comment] 2022-05-13 01:56
Thank you @swampthang ! I think this is a bug in the browser component of scribbletune. I tried the steps you shared and could reproduce the issue. I ll fix this as soon as I get some time.. however in the mean time could you please try with an earlier version of Scribbletune? I just tried with v4.1.1 and it seems to work fine there. 

I do have a [stackblitz with a working example](https://stackblitz.com/edit/scale-player) (which uses an earlier version) if you d like to take a look at how i m wiring it up. I also have a [video that shows how it s built](https://www.youtube.com/watch?v=6Ru2H-IrOWU)

**Comment by swampthang** [comment] 2022-05-13 02:11
Thanks for the quick reply! I'll check into that and report back. Thanks again.

**Comment by walmik** [comment] 2022-05-13 05:42
Hello again @swampthang I ve figured out what the issue was. I think its more of a documentation issue than a bug. In v5 we removed the ability to play a clip by itself. Now it needs a session to be created first in order to play a clip. While it now makes me wonder if we did the right thing, I d like to show you the change you ll need to do in your code if you still want to use v5. Basically create a session first and then attach a channel to it to play one or more clips. 

Start by importing the Session with,
```
import { Session } from 'scribbletune/browser';
```

And then wherever you want to play the clip,

```

I believe the reason we did this is, ultimately you d want to create something non-trivial and not just a single clip. If you get some time you can take a look at this full blown application created this way http://live.scribbletune.com/

**Comment by swampthang** [comment] 2022-05-13 13:39
I forked your example and downloaded from stackblitz (what an awesome tool, btw!). Ran create-react-app, copied the downloaded items into the newly created app. Then ran npm install. When I try npm run start, I get this message (which I've seen before in other modules)....
```
Compiled with problems:X

ERROR in ./node_modules/scribbletune/browser.js 797:14-27

Module not found: Error: Can't resolve 'fs' in '/Users/swampthang/react/scribble/node_modules/scribbletune'
```
Do you know of a way to fix this in package.json? I tried adding:
```
"browser": {
  "fs": false,
  "path": false,
  "os": false
}
```
But still get the same error.

**Comment by swampthang** [comment] 2022-05-13 22:57
I didn't see your post about the documentation issue until after I had posted about the inability to resolve 'fs' issue. Have you been able to create a local react app using your stackblitz example?

**Comment by walmik** [comment] 2022-05-14 01:19
I ll look into this once I m home later tonight however in the mean time have tried adding a property called node with a inner property called fs with its value set to false?

I think this is a fairly common problem as the browser can't make sense out of it.

**Comment by swampthang** [comment] 2022-05-14 18:03
Yea, I tried a couple of things. I've always been able to add what you mentioned and get things working. For some reason it continues to error. Here's my package.json:
```
{
  "name": "react",
  "version": "0.0.0",
  "private": true,
  "dependencies": {
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "scribbletune": "4.1"
  },
  "resolve": {
    "fallback": {
      "fs": false
    }
  },
  "node": {
    "fs": false
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  },
  "devDependencies": {
    "react-scripts": "latest"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
```
I tried with and without the resolve property. The error is always this:
```
Failed to compile.

Module not found: Error: Can't resolve 'fs' in '/Users/swampthang/react/scribble/node_modules/scribbletune'
ERROR in ./node_modules/scribbletune/browser.js 797:14-27
Module not found: Error: Can't resolve 'fs' in '/Users/swampthang/react/scribble/node_modules/scribbletune'

webpack compiled with 1 error
```
I also tried with `"fs": "empty"` (which is what used to work in previous versions)

**Comment by walmik** [comment] 2022-05-14 20:32
@swampthang I was able to reproduce this issue locally. I think it s something to do with webpack v5 (or the latest react scripts) And you are right about setting fs to empty or false etc worked in the past!

Downgrading react-scripts is the most common solve suggested in most cases along with adding some polyfills for the browser (which I believe stackblitz does behind the scenes). I downgraded react-scripts to ^4.0.3 and that worked fine. I d recommend trying that out. I do have an updated stackblitz in case you wanna download it and try that first https://stackblitz.com/edit/scale-player-pv3ntv?file=package.json 

Lemme know how it goes!

**Comment by swampthang** [comment] 2022-05-15 12:16
Ahhh. Thanks so much for the reply! The other thing I had to do is use node version 16. I'm using nvm as a node version manager so reverted from 17.0.0 to 16.13.0 and it works. Thanks again. Using node v17.0.0 I got this error when trying to 'npm run start':
```
Error: error:0308010C:digital envelope routines::unsupported
```
Check out [this stackoverflow](https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported).

**Comment by walmik** [comment] 2022-05-15 15:54
Glad to hear the issue is resolved! 

Even number versions of node are stable hence it s better to avoid the odd numbers in general (unless you are testing some of the new features in node itself)

**Comment by swampthang** [comment] 2022-05-15 18:32
Thanks, yea, I'll keep that in mind. Hey, did you get my Messenger msg? I might have a paying project you'd be interested in.

**Comment by walmik** [comment] 2022-09-12 03:51
Closing this issue @swampthang as it seems to be resolved!

**Closed by walmik** 2022-09-12 03:51 UTC
